[package]
name = "flatterer"
version = "0.3.1"
authors = ["David Raznick <kindly@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yajlish = { version = "0.3", features = ["ndjson"] } 
serde_json = "1"
tempfile = "3"
itertools = "0.10"
csv = "1"
clap = "2"
serde = {version = "1", features = ["derive"] }
pyo3 = {version = "0.14", features = ["extension-module"] }
xlsxwriter = "0.3"
crossbeam-channel="0.5"
smallvec="1.6.1"
regex="1"

[profile.release]
debug = true

[lib]
name = "flatterer"
path = "src/lib.rs"

crate-type = ["cdylib", "rlib"]

[[bin]]
name = "flatterer-cli"
path = "src/main.rs"

